version: '3'

services:
  postgres_test: 
    image: postgres:14
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgres:/data/bd
    environment:
      - POSTGRES_DB=ngb_beta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=080502
    container_name: ngb_postgres
    expose:
      - "5432"
  ngb_beta_app:
    image: ngb_beta
    build: .
    environment:
      - TZ=Asia/Shanghai
      - ENV=default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/src
      - ./env:/env
    ports:
      - "8080:8888"
    depends_on:
      - postgres_test

  headless:
      image: rendora/chrome-headless:latest
      network_mode: "host"
      tmpfs:
          - /tmp
  rendora:
      image: rendora/rendora
      network_mode: "host"
      volumes:
          - ./env/config/rendora.yml:/etc/rendora/config.yaml

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" 
    volumes:
      - ./env/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
