version: '3'

services:
  postgres_test: 
    image: postgres:14
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgres:/data/bd
    environment:
      - POSTGRES_DB=ngb_beta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=080502
    container_name: ngb_postgres
    expose:
      - "5432"
  ngb_beta_app:
    image: ngb_beta
    build: .
    environment:
      - TZ=Asia/Shanghai
      - ENV=prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/src
      - ./env:/env
    ports:
      - "8080:8888"
    depends_on:
      - postgres_test



