version: '3'

services:
  postgres: 
    image: postgres:14
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgres:/data/bd
    environment:
      - POSTGRES_DB=ngb_beta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=080502
    container_name: ngb_postgres
    expose:
      - "5432"
    restart: always
    networks:
      - ngb

  headless:
    image: rendora/chrome-headless:latest
    tmpfs:
      - /tmp
    network_mode: "host"
  rendora:
    image: rendora/rendora
    volumes:
      - ./env/config/rendora.yml:/etc/rendora/config.yaml
    network_mode: "host"

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" 
    volumes:
      - ./env/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    networks:
      - ngb

  redis:
    image: redis:6.2.5
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: ngb_redis
    volumes:
      - ./data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    tty: true
    restart: always
    networks:
      - ngb


  ngb_app:
    build: .
    environment:
      - TZ=Asia/Shanghai
      - ENV=test
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/src
      - ./env:/env
    ports:
      - "8080:8888"
    depends_on:
      - postgres
      - elasticsearch
      - rendora
      - redis
    networks:
      - ngb

networks:
  ngb:
    driver: overlay



