app:
  addr: ""

postgresql:
  user: ""
  password: ""
  dbname: "ngb_beta"
  host: ""
  port: ""

jwt:
  secret: ""

log:
  path: ""
  file: ""

mail:
  host : "smtp.xxx.com"
  port : "smtp.xxx.com:587"
  username : ""
  password : ""
  goroutine: 10


elasticsearch:
  index: ""