app:
  addr: ":8080"

postgresql:
  user: "postgres"
  password: "080502"
  dbname: "ngb_beta"
  host: "localhost"
  port: "5432"

redis:
  host: "localhost"
  port: "6379"

jwt:
  secret: "2333333"

log:
  path: "log"
  file: "log"

mail:
  host : "smtp.qq.com"
  addr : "smtp.qq.com:587"
  username : "2436201947@qq.com"
  password : "fidrbfeotqiyebbg"
  goroutine: 3

elasticsearch:
  index: "ngb_post"

rabbitmq:
  host: "localhost"
  port: "5672"
  user: "root"
  password: "root"
  exchange_name: "ngb_direct"
  routing_key: "websocket"

debug: true
